name: 'Autolabel'
description: 'Automatically label new pull requests for Eco QA process'
inputs:
  repo-token:
    required: true
    description: 'The GITHUB_TOKEN secret'

runs:
  using: 'node16'
  main: 'dist/index.js'
